#! /bin/sh

set -e

DIR=$(dirname "$(readlink -f "$0")")

IMG=$(docker build -q $DIR/.workbench)

if [ -z "$CI_PROJECT_DIR" ]; then
    INTERACTIVE="-it"
else
    INTERACTIVE=""
fi

if [ "$#" -eq 0 ]; then
    CMD=bash
else
    CMD="$@"
fi

docker run --rm \
    -v /etc/passwd:/etc/passwd \
    -v /etc/group:/etc/group \
    -v $HOME:$HOME \
    -e USER="$USER" \
    --net host \
    --privileged \
    $INTERACTIVE $IMG sudo -u ${USER} -i sh -c "cd $DIR; $CMD"
