#! /bin/sh

set -e

DIR=$(dirname "$(readlink -f "$0")")
IMG=$(docker build \
    --build-arg http_proxy="$http_proxy" \
    --build-arg https_proxy="$https_proxy" \
    --build-arg no_proxy="$no_proxy" \
    -q $DIR/.workbench
)

if [ "$#" -eq 0 ]; then
    CMD=bash
else
    CMD="$@"
fi

if [ ! -z "$CI_PROJECT_DIR" ]; then
    CONTAINER_OPTS="-v /root:/root -v /${CI_PROJECT_DIR}:/${CI_PROJECT_DIR}"
else
    CONTAINER_OPTS="-v $HOME:$HOME -it"
fi

docker run --rm \
    -e http_proxy="$http_proxy" \
    -e https_proxy="$https_proxy" \
    -e no_proxy="$no_proxy" \
    -v /etc/passwd:/etc/passwd \
    -v /etc/group:/etc/group \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --net host \
    $CONTAINER_OPTS $IMG sudo -u ${USER} -E sh -c "cd $DIR; HOME=$HOME $CMD"
